/**
 * generated by Xtext 2.14.0
 */
package org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Bind;
import org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.MondoPropertyBasedLockingPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bind</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BindImpl extends MinimalEObjectImpl.Container implements Bind
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BindImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MondoPropertyBasedLockingPackage.Literals.BIND;
  }

} //BindImpl
