/**
 * generated by Xtext 2.14.0
 */
package org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MondoPropertyBasedLockingFactoryImpl extends EFactoryImpl implements MondoPropertyBasedLockingFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MondoPropertyBasedLockingFactory init()
  {
    try
    {
      MondoPropertyBasedLockingFactory theMondoPropertyBasedLockingFactory = (MondoPropertyBasedLockingFactory)EPackage.Registry.INSTANCE.getEFactory(MondoPropertyBasedLockingPackage.eNS_URI);
      if (theMondoPropertyBasedLockingFactory != null)
      {
        return theMondoPropertyBasedLockingFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MondoPropertyBasedLockingFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MondoPropertyBasedLockingFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MondoPropertyBasedLockingPackage.PROPERTY_BASED_LOCKING_MODEL: return createPropertyBasedLockingModel();
      case MondoPropertyBasedLockingPackage.ROLE: return createRole();
      case MondoPropertyBasedLockingPackage.USER: return createUser();
      case MondoPropertyBasedLockingPackage.GROUP: return createGroup();
      case MondoPropertyBasedLockingPackage.LOCK: return createLock();
      case MondoPropertyBasedLockingPackage.BINDING: return createBinding();
      case MondoPropertyBasedLockingPackage.BIND: return createBind();
      case MondoPropertyBasedLockingPackage.ROLE_BIND: return createRoleBind();
      case MondoPropertyBasedLockingPackage.VALUE_BIND: return createValueBind();
      case MondoPropertyBasedLockingPackage.OBJECT_BIND: return createObjectBind();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PropertyBasedLockingModel createPropertyBasedLockingModel()
  {
    PropertyBasedLockingModelImpl propertyBasedLockingModel = new PropertyBasedLockingModelImpl();
    return propertyBasedLockingModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Role createRole()
  {
    RoleImpl role = new RoleImpl();
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public User createUser()
  {
    UserImpl user = new UserImpl();
    return user;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Group createGroup()
  {
    GroupImpl group = new GroupImpl();
    return group;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Lock createLock()
  {
    LockImpl lock = new LockImpl();
    return lock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Binding createBinding()
  {
    BindingImpl binding = new BindingImpl();
    return binding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Bind createBind()
  {
    BindImpl bind = new BindImpl();
    return bind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RoleBind createRoleBind()
  {
    RoleBindImpl roleBind = new RoleBindImpl();
    return roleBind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValueBind createValueBind()
  {
    ValueBindImpl valueBind = new ValueBindImpl();
    return valueBind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectBind createObjectBind()
  {
    ObjectBindImpl objectBind = new ObjectBindImpl();
    return objectBind;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MondoPropertyBasedLockingPackage getMondoPropertyBasedLockingPackage()
  {
    return (MondoPropertyBasedLockingPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MondoPropertyBasedLockingPackage getPackage()
  {
    return MondoPropertyBasedLockingPackage.eINSTANCE;
  }

} //MondoPropertyBasedLockingFactoryImpl
