/**
 * generated by Xtext 2.14.0
 */
package org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.MondoPropertyBasedLockingFactory
 * @model kind="package"
 * @generated
 */
public interface MondoPropertyBasedLockingPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mondoPropertyBasedLocking";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mondo.org/collaboration/security/mpbl/xtext/MondoPropertyBasedLocking";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mondoPropertyBasedLocking";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MondoPropertyBasedLockingPackage eINSTANCE = org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl.init();

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.PropertyBasedLockingModelImpl <em>Property Based Locking Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.PropertyBasedLockingModelImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getPropertyBasedLockingModel()
   * @generated
   */
  int PROPERTY_BASED_LOCKING_MODEL = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_BASED_LOCKING_MODEL__ROLES = 0;

  /**
   * The feature id for the '<em><b>Locks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_BASED_LOCKING_MODEL__LOCKS = 1;

  /**
   * The number of structural features of the '<em>Property Based Locking Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_BASED_LOCKING_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getRole()
   * @generated
   */
  int ROLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.UserImpl <em>User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.UserImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getUser()
   * @generated
   */
  int USER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER__NAME = ROLE__NAME;

  /**
   * The number of structural features of the '<em>User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.GroupImpl <em>Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.GroupImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getGroup()
   * @generated
   */
  int GROUP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__NAME = ROLE__NAME;

  /**
   * The feature id for the '<em><b>Users</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP__USERS = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.LockImpl <em>Lock</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.LockImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getLock()
   * @generated
   */
  int LOCK = 4;

  /**
   * The feature id for the '<em><b>Owner</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCK__OWNER = 0;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCK__PATTERN = 1;

  /**
   * The feature id for the '<em><b>Bindings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCK__BINDINGS = 2;

  /**
   * The number of structural features of the '<em>Lock</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCK_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindingImpl <em>Binding</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindingImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getBinding()
   * @generated
   */
  int BINDING = 5;

  /**
   * The feature id for the '<em><b>Param</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__PARAM = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING__VALUE = 1;

  /**
   * The number of structural features of the '<em>Binding</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINDING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindImpl <em>Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getBind()
   * @generated
   */
  int BIND = 6;

  /**
   * The number of structural features of the '<em>Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BIND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleBindImpl <em>Role Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleBindImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getRoleBind()
   * @generated
   */
  int ROLE_BIND = 7;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_BIND__ROLE = BIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Role Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_BIND_FEATURE_COUNT = BIND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ValueBindImpl <em>Value Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ValueBindImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getValueBind()
   * @generated
   */
  int VALUE_BIND = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_BIND__VALUE = BIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Value Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_BIND_FEATURE_COUNT = BIND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ObjectBindImpl <em>Object Bind</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ObjectBindImpl
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getObjectBind()
   * @generated
   */
  int OBJECT_BIND = 9;

  /**
   * The feature id for the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_BIND__OBJECT = BIND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Object Bind</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_BIND_FEATURE_COUNT = BIND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel <em>Property Based Locking Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property Based Locking Model</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel
   * @generated
   */
  EClass getPropertyBasedLockingModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel#getRoles()
   * @see #getPropertyBasedLockingModel()
   * @generated
   */
  EReference getPropertyBasedLockingModel_Roles();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel#getLocks <em>Locks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Locks</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.PropertyBasedLockingModel#getLocks()
   * @see #getPropertyBasedLockingModel()
   * @generated
   */
  EReference getPropertyBasedLockingModel_Locks();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Role#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Role#getName()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Name();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.User <em>User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.User
   * @generated
   */
  EClass getUser();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Group <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Group
   * @generated
   */
  EClass getGroup();

  /**
   * Returns the meta object for the reference list '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Group#getUsers <em>Users</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Users</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Group#getUsers()
   * @see #getGroup()
   * @generated
   */
  EReference getGroup_Users();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock <em>Lock</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lock</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock
   * @generated
   */
  EClass getLock();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getOwner <em>Owner</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Owner</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getOwner()
   * @see #getLock()
   * @generated
   */
  EReference getLock_Owner();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pattern</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getPattern()
   * @see #getLock()
   * @generated
   */
  EReference getLock_Pattern();

  /**
   * Returns the meta object for the containment reference list '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getBindings <em>Bindings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Bindings</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Lock#getBindings()
   * @see #getLock()
   * @generated
   */
  EReference getLock_Bindings();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding <em>Binding</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binding</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding
   * @generated
   */
  EClass getBinding();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Param</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding#getParam()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_Param();

  /**
   * Returns the meta object for the containment reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Binding#getValue()
   * @see #getBinding()
   * @generated
   */
  EReference getBinding_Value();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Bind <em>Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bind</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.Bind
   * @generated
   */
  EClass getBind();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.RoleBind <em>Role Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role Bind</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.RoleBind
   * @generated
   */
  EClass getRoleBind();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.RoleBind#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.RoleBind#getRole()
   * @see #getRoleBind()
   * @generated
   */
  EReference getRoleBind_Role();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ValueBind <em>Value Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Bind</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ValueBind
   * @generated
   */
  EClass getValueBind();

  /**
   * Returns the meta object for the attribute '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ValueBind#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ValueBind#getValue()
   * @see #getValueBind()
   * @generated
   */
  EAttribute getValueBind_Value();

  /**
   * Returns the meta object for class '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ObjectBind <em>Object Bind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Bind</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ObjectBind
   * @generated
   */
  EClass getObjectBind();

  /**
   * Returns the meta object for the reference '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ObjectBind#getObject <em>Object</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Object</em>'.
   * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.ObjectBind#getObject()
   * @see #getObjectBind()
   * @generated
   */
  EReference getObjectBind_Object();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MondoPropertyBasedLockingFactory getMondoPropertyBasedLockingFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.PropertyBasedLockingModelImpl <em>Property Based Locking Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.PropertyBasedLockingModelImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getPropertyBasedLockingModel()
     * @generated
     */
    EClass PROPERTY_BASED_LOCKING_MODEL = eINSTANCE.getPropertyBasedLockingModel();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_BASED_LOCKING_MODEL__ROLES = eINSTANCE.getPropertyBasedLockingModel_Roles();

    /**
     * The meta object literal for the '<em><b>Locks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY_BASED_LOCKING_MODEL__LOCKS = eINSTANCE.getPropertyBasedLockingModel_Locks();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__NAME = eINSTANCE.getRole_Name();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.UserImpl <em>User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.UserImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getUser()
     * @generated
     */
    EClass USER = eINSTANCE.getUser();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.GroupImpl <em>Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.GroupImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getGroup()
     * @generated
     */
    EClass GROUP = eINSTANCE.getGroup();

    /**
     * The meta object literal for the '<em><b>Users</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP__USERS = eINSTANCE.getGroup_Users();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.LockImpl <em>Lock</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.LockImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getLock()
     * @generated
     */
    EClass LOCK = eINSTANCE.getLock();

    /**
     * The meta object literal for the '<em><b>Owner</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCK__OWNER = eINSTANCE.getLock_Owner();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCK__PATTERN = eINSTANCE.getLock_Pattern();

    /**
     * The meta object literal for the '<em><b>Bindings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCK__BINDINGS = eINSTANCE.getLock_Bindings();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindingImpl <em>Binding</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindingImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getBinding()
     * @generated
     */
    EClass BINDING = eINSTANCE.getBinding();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__PARAM = eINSTANCE.getBinding_Param();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINDING__VALUE = eINSTANCE.getBinding_Value();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindImpl <em>Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.BindImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getBind()
     * @generated
     */
    EClass BIND = eINSTANCE.getBind();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleBindImpl <em>Role Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.RoleBindImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getRoleBind()
     * @generated
     */
    EClass ROLE_BIND = eINSTANCE.getRoleBind();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLE_BIND__ROLE = eINSTANCE.getRoleBind_Role();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ValueBindImpl <em>Value Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ValueBindImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getValueBind()
     * @generated
     */
    EClass VALUE_BIND = eINSTANCE.getValueBind();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE_BIND__VALUE = eINSTANCE.getValueBind_Value();

    /**
     * The meta object literal for the '{@link org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ObjectBindImpl <em>Object Bind</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.ObjectBindImpl
     * @see org.mondo.collaboration.security.mpbl.xtext.mondoPropertyBasedLocking.impl.MondoPropertyBasedLockingPackageImpl#getObjectBind()
     * @generated
     */
    EClass OBJECT_BIND = eINSTANCE.getObjectBind();

    /**
     * The meta object literal for the '<em><b>Object</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_BIND__OBJECT = eINSTANCE.getObjectBind_Object();

  }

} //MondoPropertyBasedLockingPackage
