/*
 * generated by Xtext 2.14.0
 */
package org.mondo.collaboration.security.mpbl.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mondo.collaboration.security.mpbl.xtext.parser.antlr.internal.InternalMondoPropertyBasedLockingParser;
import org.mondo.collaboration.security.mpbl.xtext.services.MondoPropertyBasedLockingGrammarAccess;

public class MondoPropertyBasedLockingParser extends AbstractAntlrParser {

	@Inject
	private MondoPropertyBasedLockingGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMondoPropertyBasedLockingParser createParser(XtextTokenStream stream) {
		return new InternalMondoPropertyBasedLockingParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PropertyBasedLockingModel";
	}

	public MondoPropertyBasedLockingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MondoPropertyBasedLockingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
