/*
 * generated by Xtext 2.14.0
 */
package org.mondo.collaboration.security.mpbl.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MondoPropertyBasedLockingStandaloneSetup extends MondoPropertyBasedLockingStandaloneSetupGenerated {

	def static void doSetup() {
		new MondoPropertyBasedLockingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
